### ISSUE TITLE
[SPRING] Please make sure to cache the permissions to allow quick app start

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/ios-cmp-app#112]
Please cache last vendors, custom vendors, purposes and custom purposes settings plus fallback if none were fetched so far, so we can get the settings for quick start of the app and also in bad network conditions.

**Comment by pkcpkc** [comment]
Offline, too!

**Comment by s-hintz** [comment]
Will this change how often `onConsentReady` is be called?

**Comment by andresilveirah** [comment]
@pkcpkc @s-hintz we're going to implement this feature in the following way.

We're going to cache the contents of the `GDPRUserConsent` instance you get in the `onConsentReady` in the `UserDefaults` and give you a method/attribute that you can call to get the cached version of the user consents.

Also, we're adding a delegate method:
```swift
onError(error: GDPRConsentViewControllerError, cachedConsents: GDPRUserConsent)
````
Which, as you might expect, will give you the cached user consents in case of an error (e.g. no internet connection). 


> Will this change how often onConsentReady is be called?
@s-hintz it will not.

**Comment by s-hintz** [comment]
Great! When will it be available for us?

**Comment by andresilveirah** [comment]
@s-hintz @pkcpkc , you're now able to access the attribute `.userConsents: GDPRUserConsent`. 
We initialise this attribute with default values at construction time and will mutate it once we get the response from our API.

We decided against adding a second `onError` delegate method (like the one I mentioned in the comment above), since you can access the `.userConsents` at any time you have an instance of `GDPRViewController.
