### ISSUE TITLE
[SPRING] Unit Tests incl. coverage report and UI-Tests with demo

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/ios-cmp-app#156]

**Comment by andresilveirah** [comment]
@pkcpkc I believe my colleague Atanur answered you either via email or slack, but for the sake of completeness, I'll post a screenshot of the report here too. 

<img width="682" alt="Screenshot 2020-06-03 at 11 49 38" src="https://user-images.githubusercontent.com/228650/84007518-d993e100-a970-11ea-87a4-566c26d48c59.png">

We dont't have native UI tests because we use Appium and other tools to do end-to-end testing. Those are in another repo but we plan to bring them to each of the SDK's repos as well.

**Comment by andresilveirah** [comment]
@pkcpkc I'm closing this issue as I think it has been answered.
