### ISSUE TITLE
[SPRING] We need proper error codes from the SDK and not just: 0

### ISSUE THREAD

**Issue by s-hintz** [SourcePointUSA/ios-cmp-app#227]
**Describe the bug**
When the SDK encounters this error while initial app start:
"Something went wrong in the webview (code: 99, title: general error, stackTrace: Script error.)"
The the delegate method `public func onError(error: GDPRConsentViewControllerError?)` is called.
But the `error.code` is not 99 as expected, but 0.
So we currently need to compare:
error.description.contains("code 99")
to avoid that our app is blocked during app start, by trying to dismiss the empty GDPRConsentViewController ourselves .

**Ideally such error handling should not be necessary by our app.
The GDPRConsentViewController should know to dismiss itself on error.**

Used error codes should also be documented in the documentation of the SourcePoint SDK.

**About your campaign (please complete the following information):**
 - Account Id: 75
 - Property Id: 5593
 - Property Name: "BILD-NEWS-IOS"
 - Campaign Env: .Public
 - Targeting Params: ["native": "true"]
 - AuthId: nil

** About your environment **
 - SDK version: 5.2.5
 - Device: iPhone 11
 - OS: iOS 13

**To Reproduce**
Dropping the connection (or setting 403) for the url sourcepoint.mgr.consensu.org before app was ever started (initial app start).

**Expected behavior**
The error code should not be 0.
The app should not freeze after:
consentViewController.loadMessage(forAuthId: nil)

**Screenshots**
![Screenshot 2020-08-18 at 15 55 22](https://user-images.githubusercontent.com/39526001/90522035-8954ae80-e16b-11ea-86d3-40b36d8f27ec.png)

**Additional context**
When dropping connection (or setting 403) for the url sourcepoint.mgr.consensu.org before app was ever started (initial app start), then the home screen is freezed and no interaction is possible within the app.
It works fine when all sourcepoint-related calls are blocked, but not when this single call is blocked - it also works fine, when 1 additional call of cdn.privacy-mgmt OR notice.sp-prod OR wrapper-api.sp-prod is blocked too.
IS:
dropping connection for certain url freezes app
SHOULD:
app should never freeze because something in cmp-backend went wrong

**Comment by andresilveirah** [comment]
@s-hintz there might be several issues mixed up here. Let me try to separate them and ask you a few questions.

- [ ] 1. Error code is different than you expected
- [ ] 2. The app is "frozen" when you drop the connection to `sourcepoint.mgr.consensu.org`.
- [ ] 3. Error codes are not documented.

## 1. Error code is different than you expected. 
Indeed, even though you see in the error message a "code: 99" that is just part of the error message, not a property `code` of the error. We can certainly have a look at that. 
>So we currently need to compare:
error.description.contains("code 99")
to avoid that our app is blocked during app start, by trying to dismiss the empty GDPRConsentViewController ourselves .

Why do you have to do this comparison? Is there another error in which you don't dismiss the ViewController?

## 2. App is "frozen" when dropping connection to `sourcepoint.mgr.consensu.org`
I'm not sure how you implemented that on your side. My assumption the app is frozen because none of the callbacks were called. Is that correct?

## 3. Error codes are not documented.
That's also a fair point. We currently don't have an standardisation of the error codes. But, just like item number 1, this is also something we should look into.

**Comment by s-hintz** [comment]
`onError` can be called from anywhere anytime so we should not just try to dismiss something all the time, but only in cases we have found that this is needed.

The app is frozen because the GDPRConsentViewController is open but the user can not close it.

**Comment by andresilveirah** [comment]
@s-hintz can you give me one example in which you don't want to dismiss the `GDPRConsentViewController` when an error happens (`onError`)?

When you do get the `onError`, if the error contains the correct code (`99`) in this case, will this fix the issue for you?

**Comment by s-hintz** [comment]
The method which dismisses the GDPRConsentViewController will dismiss any other controller which might be open at that time.

**Comment by andresilveirah** [comment]
@s-hintz got you. So you avoid `dismiss` at all costs. If you have proper error codes, will this fix the issue for you?
Something like:
```
1. NoInternetConnection(code: 1)
2. WebViewError(code: 99) 
3. ...
```

**Comment by s-hintz** [comment]
Today we have decided that we will check in onError if the GDPRConsentViewController is open and then we will close it.
So we will remove the check for 99.

But we still do not know when we should notify the user about errors and when not.
When the Consent Message is displayed to the user and saving fails the user should know about it.
But when the app starts again without showing the Consent Message then the user should not be bothered when onError is called.
At the moment we do not know how to distinguish those use cases.
________________________________
Von: André Herculano <notifications@github.com>
Gesendet: Mittwoch, 19. August 2020 10:01
An: SourcePointUSA/ios-cmp-app <ios-cmp-app@noreply.github.com>
Cc: Hintz, Stefan <stefan.hintz@spring-media.de>; Mention <mention@noreply.github.com>
Betreff: Re: [SourcePointUSA/ios-cmp-app] [SPRING] We need proper error codes from the SDK and not just: 0 (#227)


@s-hintz<https://github.com/s-hintz> got you. So you avoid dismiss at all costs. If you have proper error codes, will this fix the issue for you?
Something like:

1. NoInternetConnection(code: 1)
2. WebViewError(code: 99)
3. ...

**Comment by andresilveirah** [comment]
I think I understand your use case now @s-hintz . As a rule of thumb, you will want to inform the user about an error only if the `GDPRConsentViewController` was presented. You could set a flag (eg. `wasConsentPresented`) to true during `onConsentUIWillShow`. If the `onError` is called, you check this flag and decide if you should inform the user or not. 

Would that work for you?

**Comment by s-hintz** [comment]
That is a good idea.
And what is when onError was called from the Privacy Manager?
And what is when onError was called while enabling the social network vendors?

**Comment by andresilveirah** [comment]
@s-hintz good points.

>And what is when onError was called from the Privacy Manager?

This case is easy. The `onConsentUIWillShow` is called also when the Privacy Manager is presented. So the `wasConsentPresented` flag would be set to true and if the `onError` is called, you'll know you should give the user some feedback. 

> And what is when onError was called while enabling the social network vendors?

That's when calling the `customConsentTo`, right? In that case, the `onConsentUIWillShow` won't be called so the flag wouldn't be set to true. But you still need to present the user with an error message if something fails at this stage. 

So perhaps we need to expand the idea of the flag a bit further. Instead of `wasConsentPresented` we could call it `shouldWarnUserIfErrorHappens` (I'm not good with names...) and that flag would be set to true in two spots:
1. inside `onConsentUIWillShow`
2. every time you call `customConsentTo`

The flag would be reset to false in 3 spots:
1. inside `onConsentReady`
2. inside `onError`
3. inside the completion handler you pas to `customConsentTo` method

With the approach above, I believe we cover all cases. It's more work than checking error codes but I think it's semantically more accurate.  What do you think?

**Comment by s-hintz** [comment]
This looks very good to me.
Please add it to the SDK-Documentation and we are fine.

**Comment by andresilveirah** [comment]
@s-hintz I believe the discussion above deserves more than a note on the Readme so I created a [wiki for it](https://github.com/SourcePointUSA/ios-cmp-app/wiki/When-to-warn-users-when-an-error-happens%3F). Let me know what you think.
