### ISSUE TITLE
[SPRING] "Alle akzeptieren" does NOT enable all vendors BILD iOS and Android

### ISSUE THREAD

**Issue by pkcpkc** [SourcePointUSA/ios-cmp-app#244]
Clicking 'Alle akzeptieren' in ConsentLayer (or in PM) does not accept everything.
When you open the privacy manager, there are still opted-out categories in the legitimate interest section.

s2r

- start cmp app for the first time
- tab 'Alle akzeptieren'
- open menu
- tab 'Privatssphäreeinstellungen'
- open legitimate interest section

IS:
button called 'Alle akzeptieren' does not opt-in everything

SHOULD
a button called 'Alle akzeptieren' should opt-in everything

additional information:
when tabbing Einstellungen oder ablehnen in consent layer to get to the PM and going there to the legitimate interest category, both interests are opted-in (so default setting is working, but Alle akzeptieren button seems to change that)

**Comment by andresilveirah** [comment]
Thanks for reporting this issue @pkcpkc . @atanurdemirci can you have a look at their vendor list and their PM? At first glance, this seems to be a configuration issue. Let me know if I can help you debug it.

**Comment by atanurdemirci** [comment]
I am closing this issue, this happened due to a change on the global vendor list (Amobee) and should have been resolved in the meanwhile.

**Comment by atanurdemirci** [comment]
Reopening in order to fix issues with Vendors having only special purposes enabled on the global vendor list

**Comment by haerju** [comment]
@pkcpkc This is issue should be solved save for one vendor "ad pepper" that apparently hasn't selected any IAB purposes or  features. Hence there is nothing to accept for a user. I forwarded this issue to your project team and we will make a decision on how best proceed. This is an issue with the GVL rather than a system issue and requires a business decision to get resolved.

@andresilveirah this ticket can be closed.
