### ISSUE TITLE
[NMT] Disable consent for a list of vendors

### ISSUE THREAD

**Issue by toupper** [SourcePointUSA/ios-cmp-app#276]
@andresilveirah  we want to **disable** the consent for a list of vendor ids, is that possible with the current implementation of `GDPRConsentViewController` ? is there a function or a combination of steps to achieve that? Thanks

**Comment by andresilveirah** [comment]
Hi @toupper what do you mean disabling consent for a couple of vendors? The SDK itself doesn't implement that but I, if I understand the use case correctly, you have 2 options:
1. (only valid for non-IAB vendors) during `onConsentReady` ignore those vendors ids you're aiming to disable. That unfortunately doesn't work for IAB vendors since the consent is encoded directly in the consent string. 
2. Removing those vendors from the vendor list within our dashboard.

FYI @atanurdemirci

**Comment by toupper** [comment]
Hi @andresilveirah @atanurdemirci , We want to programatically be able to undo the user given consent for some vendors. Same way we use 
```
func customConsentTo(
        vendors: [String],
        categories: [String],
        legIntCategories: [String],
        completionHandler: @escaping (GDPRUserConsent) -> Void)
```
to add these ids to the consent profile of the user, we want to be able to remove them. Something like

``` func removeCustomConsentTo(vendors: [String]...```

We cannot use `onConsentReady` because we want to be able to trigger that at any time of the app lifecycle, not only when the consent is ready.
Furthermore, as a workaround until the function is available in the sdk, we are thinking  about these steps to achieve it:
- Create a `GDPRAction` with .`saveAndExit` type
- Encode user json (`SPGDPRArbitraryJson`?) consent using `JSONEncoder` and set it to data property of `GDPRAction`
- Send this action to SDK using `onAction` method

What do you think? would that work or you think there is an easier way for that? We can have a videocall if it is easier for you.
Thanks a lot!

**Comment by andresilveirah** [comment]
@toupper I see the point on having a `removeCustomConsent` method. I can't promise you an ETA on that because we're committed to other priorities right now. 

Regarding your work around using the `.saveAndExit` that would work. But it's quite a bit of effort on your side. You'll need to inspect the exact data the `.saveAndExit` needs in order for our API to accept its payload. Also, keep in mind this data might change (we simply get it from the frontend and forward it to the API). If you are willing to put this effort, I'm confident it will achieve the result you're looking for.

**Comment by andresilveirah** [comment]
We're still not sure we'll have support to this feature. Closing this issue.
