### ISSUE TITLE
tvOS Support for Swift Package Manager

### ISSUE THREAD

**Issue by Sherlouk** [SourcePointUSA/ios-cmp-app#419]
**Describe the bug**

Currently the CocoaPod spec does add support for iOS and tvOS, where SwiftPackageManager only supports iOS (and fails to compile against tvOS due to the WebKit dependency).

It would be nice if some compiler conditions were added `#if os(iOS)` in order to add support for tvOS.

**Comment by andresilveirah** [comment]
Hi @Sherlouk sorry for the delay replying you. For the time being, SDK v7 is still lacking support to tvOS. However, we'll work on supporting SPM for v6. It'll be supported on v7 as well, but unfortunately, the solution is not yet ready.

**Comment by clausjoergensen** [comment]
Seems some work was done in #436 but the Package.swift still only declares iOS support

**Comment by andresilveirah** [comment]
Correct @clausjoergensen we still didn't manage declare support to both tvOS and iOS using the same `Package.swift`.

You could try using one of our [XCFrameworks](https://github.com/SourcePointUSA/ios-cmp-app/releases/tag/7.1.1) instead.

**Comment by clausjoergensen** [comment]
> Correct @clausjoergensen we still didn't manage declare support to both tvOS and iOS using the same `Package.swift`.
> 
> You could try using one of our [XCFrameworks](https://github.com/SourcePointUSA/ios-cmp-app/releases/tag/7.1.1) instead.

Hey, I can confirm this works. But since we're consuming the main framework via. SPM, we'd really like to consume the tvOS portion as well.

Checking in a binary isn't really a viable solution (and nor should it be)

Any timeline for when the tvOS implementation will be available as a Package? I see you're actively working on it.

**Comment by andresilveirah** [comment]
Hi @clausjoergensen that's correct, we put effort in supporting both via SPM, but it turned out to be much harder than I anticipated. We have since paused development there in order to focus on other, higher priority items on our roadmap. 

I unfortunately don't have an ETA for you regarding SPM support for tvOS. However, I'd be glad to review and merge a PR if you'd like to submit one.

**Comment by andresilveirah** [comment]
I feel your pain @Sherlouk and I agree it's a fair feature request. Unfortunately we don't have it on our roadmap and keeping it as an issue on our repo wouldn't help. As you may be aware, the number of open issues a library has, more or less indicates the health of that repo, I feel keeping an issue open that is not planned to be resolved in the near future isn't exactly accurate either.
