### ISSUE TITLE
Ambiguous use of 'loadMessage'

### ISSUE THREAD

**Issue by clausjoergensen** [SourcePointUSA/ios-cmp-app#475]
I don't know what you were thinking when you wrote this code:

```
    public func loadMessage(forAuthId authId: String? = nil, publisherData: [String: String]? = [:]) {
        loadMessage(forAuthId: authId, publisherData: publisherData?.mapValues { AnyEncodable($0) })
    }

    public func loadMessage(forAuthId authId: String? = nil, publisherData: SPPublisherData? = [:]) {
```

Means nobody can use the optional overload, or pass in `[:]` directly for that matter.

Like c'mon, stop shipping code that doesn't compile.

**Comment by andresilveirah** [comment]
Hi @clausjoergensen I get it, it must be frustrating to you to rename a parameter or explicitly declare its type. 
However, that was intentional in oder to change `SPPublisherData`'s underline type from `[String: String]` to `[String: AnyEncodable]` _while_ keeping changes to the public interface `SPSDK` to a minimum.

While that transition is not perfect (as you noticed yourself), we considered a good compromise, it received a bump to the minor version from `7.1.1` to `7.2.0` and we briefly mentioned it in the [CHANGELOG](https://github.com/SourcePointUSA/ios-cmp-app/blob/develop/CHANGELOG.md#720-june-23-2023).
