### ISSUE TITLE
Sharing Consent in a WKWebView

### ISSUE THREAD

**Issue by matrad** [SourcePointUSA/ios-cmp-app#480]
In your Readme you write in the section `Sharing consent with a WKWebView` Details about sharing a WebView Consent in a WebView.

You provided this Code:

```
// somewhere earlier in your app's lifecycle
var userConsents: SPUserData?

func onSPFinished(userData: SPUserData) {
    userConsents = userData
}

let webview = WKWebView()
if let userConsents = userConsents {
    webview.load(URLRequest(URL(string: "https://my-url.com/?_sp_pass_consent=true")!))
    webview.preloadConsent(from: userConsents)
} else {
    webview.load(URLRequest(URL(string: "https://my-url.com/")!)) // load url without _sp_pass_consent=true
}
```

This code works if we load a Website from a Remote-URL & Remote-Page.

We're currently loading a static HTML into our WebView (with a Remote Base URL) and our Own optimizations for displaying the Content within our App:

```
webview.loadHTMLString(htmlContent, baseURL: remoteUrl)
```

My question is how do I can share the Consent with this method. Currently we shared it (in the older SDK Version 5.x) with a static authId, and set the authId Cookie via `webview.setConsentFor(authId: uuidString)`, load the GDPR Manager with `consentManager.loadMessage(forAuthId: UIDevice.current.identifierForVendor?.uuidString)`.

Is this the correct way to share the Consent? Why did you removed this example in the Readme?

**Comment by andresilveirah** [comment]
Hi @matrad let me address your points in reverse order:

> Why did you removed this example in the Readme?

Sharing consent between native and web used to rely on authenticated consent and thus would impose on the app to give an unique identifier to the user. That's not ideal for several reasons:
1. Unique identifiers are usually frowned upon by the privacy regulators.
2. Authenticated consent is not efficient since the web script would have to request consent data from our endpoints when the native SDK had all that data locally.
3. Authenticated consent doesn't work for cases when the client decides to opt-out of server-side consent storage (a feature our CMP offers). 

We redesigned the way the native SDK shares consent with the webview (and the web script) in order to address all the constraints above.

> We're currently loading a static HTML into our WebView (with a Remote Base URL) and our Own optimizations for displaying the Content within our App. Is this the correct way to share the Consent?

That _should_ work just the same way as in our example, but instead of using webview's `.load(URLRequesst)` you use `.loadHTMLString(String, baseURL: URL)`. E.g.
```swift
var userConsents: SPUserData?

func onSPFinished(userData: SPUserData) {
    userConsents = userData
}

let webview = WKWebView()
if let userConsents = userConsents {
    webview.loadHTMLString(htmlContent, baseURL: yourUrl + "?_sp_pass_consent=true")
    webview.preloadConsent(from: userConsents)
} else {
    webview.loadHTMLString(htmlContent, baseURL: yourUrl)
}
```

I admit though that I haven't tested that feature using `.loadHTMLString`, only `.load`. I'll keep this issue open and wait for your feedback, is that ok?

**Comment by matrad** [comment]
Hello,

that's ok.

What is also not so nice for us is that we need to modify the BaseURL, because it impacts on tracking.
The best would be if we could set a javascript-variable in the htmlContent to enable the sp_pass_consent - Flag.

Thank you

**Comment by andresilveirah** [comment]
Got it. We evaluated using a js variable, but there were a number of issues with that approach (iOS pausing js runtime while the WebView is offscreen, for example). I'm afraid adding the query param is the only solution for now.
