### ISSUE TITLE
Improve landscape UX

### ISSUE THREAD

**Issue by jamesrb1** [SourcePointUSA/ios-cmp-app#530]
Hello!

Our app defaults to a landscape orientation, and the included UX does not work well because there is no exit/continue button visible. To see the continue button you need to scroll, which is not a typical requirement for a dialog. Additionally, you need to scroll the top part of the dialog or it will not show the buttons because the dialog embeds one scrollview in another. Please see the video for details.

The UX here is critically important as it is part of our onboarding process. If a user can't figure out how to navigate past this screen then we will lose them. Given how difficult it is to get past this screen we expect it to be a major problem.

https://github.com/SourcePointUSA/ios-cmp-app/assets/109382862/c900f75c-4dac-49c5-a954-17be693d9718

Thank you,

James

**Comment by andresilveirah** [comment]
Hi @jamesrb1 , the UI of the consent message can be changed in your property page in Sourcepoint's portal. Users are expected to create their own message UI and tweak it in order to best serve their needs. Feel free to contact your account manager he/she will be able to guide you customising your message if you need help.
